import { allowedGuesses as fiveLetterGuesses } from "../between/content";
import { generatedAllowedGuesses as sevenLetterGuesses } from "../shared/generated/allowedGuesses7";
import { generatedAllowedGuesses as sixLetterGuesses } from "../wortcode/generated/allowedGuesses";
import { generatedAllowedGuesses as fourLetterGuesses } from "../wortleiter/generated/allowedGuesses";
import type { WordsByLength } from "../wordLengths";

export const WORTTREFFER_CONTENT_VERSION = 3;

export const worttrefferTargetsByLength = {
  4: [
    "affe",
    "auge",
    "baum",
    "berg",
    "brot",
    "buch",
    "dach",
    "dorf",
    "feld",
    "glas",
    "haus",
    "kind",
    "mond",
    "ring",
    "sand",
    "wald",
    "wind",
    "zelt",
  ],
  5: [
    "abend",
    "ampel",
    "apfel",
    "blume",
    "danke",
    "eimer",
    "farbe",
    "frage",
    "glanz",
    "honig",
    "insel",
    "kerze",
    "klang",
    "krone",
    "lampe",
    "licht",
    "mauer",
    "nacht",
    "nadel",
    "pause",
    "preis",
    "regen",
    "reise",
    "salat",
    "spatz",
    "tafel",
    "traum",
    "wolke",
    "zange",
  ],
  6: [
    "banane",
    "blumen",
    "bruder",
    "fragen",
    "garten",
    "kaffee",
    "kuchen",
    "laufen",
    "mantel",
    "mutter",
    "schule",
    "sommer",
    "wasser",
    "winter",
    "zimmer",
  ],
  7: [
    "abstand",
    "antwort",
    "brunnen",
    "fenster",
    "freitag",
    "gebirge",
    "gedicht",
    "heizung",
    "kapitel",
    "kleider",
    "kompass",
    "pflanze",
    "schrank",
    "schwarz",
    "spieler",
    "theater",
    "wohnung",
    "zeichen",
    "zeitung",
  ],
} as const satisfies WordsByLength;

export const worttrefferGuessWordsByLength = {
  4: Array.from(new Set([...worttrefferTargetsByLength[4], ...fourLetterGuesses])).sort(),
  5: Array.from(new Set([...worttrefferTargetsByLength[5], ...fiveLetterGuesses])).sort(),
  6: Array.from(new Set([...worttrefferTargetsByLength[6], ...sixLetterGuesses])).sort(),
  7: Array.from(new Set([...worttrefferTargetsByLength[7], ...sevenLetterGuesses])).sort(),
} as const satisfies WordsByLength;

export const answerWords = Object.values(worttrefferTargetsByLength).flat();
export const guessWords = Object.values(worttrefferGuessWordsByLength).flat();
