import { generatedAllowedGuesses } from "./generated/allowedGuesses";

export const WORTCODE_CONTENT_VERSION = 1;
export const WORTCODE_WORD_LENGTH = 6;
export const WORTCODE_MAX_ATTEMPTS = 8;

export const answerWords = [
  "banane",
  "blumen",
  "bruder",
  "fragen",
  "garten",
  "kaffee",
  "kuchen",
  "laufen",
  "mantel",
  "mutter",
  "schule",
  "sommer",
  "speise",
  "straße",
  "wasser",
  "winter",
  "zimmer"
] as const;

export const guessWords = Array.from(new Set([
  ...answerWords,
  ...generatedAllowedGuesses,
  "ananas",
  "anders",
  "arbeit",
  "balkon",
  "besser",
  "bilder",
  "bitter",
  "blitze",
  "brille",
  "decken",
  "denken",
  "doppel",
  "dürfen",
  "farben",
  "finger",
  "flügel",
  "freude",
  "gabeln",
  "geigen",
  "gesund",
  "grenze",
  "halten",
  "himmel",
  "hunger",
  "kaufen",
  "keller",
  "kerzen",
  "kleine",
  "koffer",
  "kommen",
  "können",
  "lernen",
  "messer",
  "müssen",
  "preise",
  "reisen",
  "sachen",
  "singen",
  "spiele",
  "stille",
  "suchen",
  "teller",
  "trinke",
  "warten",
  "werden",
  "wissen",
  "wollen",
  "zahlen"
])).sort();
