import { allowedGuesses as fiveLetterGuesses } from "../between/content";
import { generatedAllowedGuesses as sevenLetterGuesses } from "../shared/generated/allowedGuesses7";
import type { WordsByLength } from "../wordLengths";

import { generatedAllowedGuesses as sixLetterGuesses } from "./generated/allowedGuesses";

export const WORTCODE_CONTENT_VERSION = 2;

export const wortcodeTargetsByLength = {
  5: [
    "ampel",
    "apfel",
    "blume",
    "farbe",
    "frage",
    "honig",
    "insel",
    "kerze",
    "nacht",
    "reise",
    "tafel",
    "wolke",
  ],
  6: [
    "banane",
    "blumen",
    "bruder",
    "fragen",
    "garten",
    "kaffee",
    "kuchen",
    "laufen",
    "mantel",
    "mutter",
    "schule",
    "sommer",
    "speise",
    "straße",
    "wasser",
    "winter",
    "zimmer",
  ],
  7: [
    "abstand",
    "antwort",
    "brunnen",
    "fenster",
    "freitag",
    "gebirge",
    "gedicht",
    "heizung",
    "kapitel",
    "kompass",
    "pflanze",
    "schrank",
    "schwarz",
    "spieler",
    "theater",
    "wohnung",
    "zeichen",
    "zeitung",
  ],
} as const satisfies WordsByLength;

export const wortcodeGuessWordsByLength = {
  5: Array.from(new Set([...wortcodeTargetsByLength[5], ...fiveLetterGuesses])).sort(),
  6: Array.from(new Set([
    ...wortcodeTargetsByLength[6],
    ...sixLetterGuesses,
    "ananas",
    "anders",
    "arbeit",
    "balkon",
    "besser",
    "bilder",
    "bitter",
    "blitze",
    "brille",
    "decken",
    "denken",
    "doppel",
    "dürfen",
    "farben",
    "finger",
    "flügel",
    "freude",
    "gabeln",
    "geigen",
    "gesund",
    "grenze",
    "halten",
    "himmel",
    "hunger",
    "kaufen",
    "keller",
    "kerzen",
    "kleine",
    "koffer",
    "kommen",
    "können",
    "lernen",
    "messer",
    "müssen",
    "preise",
    "reisen",
    "sachen",
    "singen",
    "spiele",
    "stille",
    "suchen",
    "teller",
    "trinke",
    "warten",
    "werden",
    "wissen",
    "wollen",
    "zahlen",
  ])).sort(),
  7: Array.from(new Set([...wortcodeTargetsByLength[7], ...sevenLetterGuesses])).sort(),
} as const satisfies WordsByLength;

export const answerWords = Object.values(wortcodeTargetsByLength).flat();
export const guessWords = Object.values(wortcodeGuessWordsByLength).flat();
